name: health
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.6

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  english_words: ^4.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  table_calendar: ^3.0.0
  intl: ^0.20.2 
  flutter_reorderable_list: ^1.3.1
  flutter_charts: ^0.5.2
  fl_chart: ^1.0.0
  collection: ^1.15.0
  flutter_launcher_icons: ^0.14.4
  firebase_storage: ^12.4.7
  image_picker: ^1.1.2
  firebase_core: ^3.14.0
  video_player: ^2.9.2
  location: ^8.0.1
  geolocator: ^14.0.1
  flutter_naver_map: ^1.3.0+1
  auto_size_text: ^3.0.0
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
 

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  xml2json: ^6.2.7
  html: ^0.15.0
  flutter_lints: ^6.0.0
  shared_preferences: ^2.0.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
 

flutter:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Oswald
      fonts:
       - asset: assets/fonts/Oswald-VariableFont_wght.ttf

  assets:
    - assets/
    - assets/videos/
  uses-material-design: true

