name: health
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  english_words: ^4.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  table_calendar: ^3.0.0
  intl: ^0.17.0 
  flutter_reorderable_list: ^1.3.1
  flutter_charts: ^0.5.2
  fl_chart: ^0.68.0

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.0.1
  xml2json: ^5.3.2
  html: ^0.15.0
  flutter_lints: ^2.0.0
  shared_preferences: ^2.0.6
 

flutter:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Oswald
      fonts:
       - asset: assets/fonts/Oswald-VariableFont_wght.ttf

  assets:
    - assets/
  uses-material-design: true

